default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-xml
        files: \.xml(\.dist)?$
        types: [file]
      - id: check-yaml
        exclude: ^docs/az/mkdocs\.yml$
      - id: check-yaml
        name: check yaml (mkdocs)
        files: ^docs/az/mkdocs\.yml$
        args: [--unsafe]
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: check-packages
        name: check-packages
        entry: composer run check-packages
        language: system
        files: (composer\.json$|^packages/)
        pass_filenames: false

      - id: format
        name: format
        entry: composer run format -- --path-mode=intersection
        language: system
        files: \.php$
        require_serial: true

      - id: check-docs
        name: check-docs
        entry: composer run check-docs
        language: system
        files: (^packages/.*\.php$|^bin/docs\.php$)
        pass_filenames: false

      - id: type-check
        name: type-check
        entry: composer run type-check
        language: system
        files: \.php$
        pass_filenames: false

      - id: test
        name: test
        entry: composer run test
        language: system
        stages: [pre-push]
        pass_filenames: false

      - id: secure
        name: secure
        entry: composer run secure
        language: system
        stages: [pre-push]
        pass_filenames: false
