[build]
publish = "docs/site"
command = "pip install -r docs/az/requirements.txt && php bin/build-docs.php"

[build.environment]

PYTHON_VERSION = "3.12"

PHP_VERSION = "8.3"

[context.production.environment]
PRIVATE_DOCS_REQUIRED = "1"

[[headers]]
for = "/assets/javascripts/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/stylesheets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
